### ISSUE TITLE
How to handle Unicode String?

### ISSUE THREAD

**Issue by jonahfang** [strahe/sanic-redis#1]
My code like this:

```
    with await request.app.redis as r:
        await r.set('key', 'value2中文')
        result = await r.get('key')
        return json({'result':result})
```
I just get something like this:

```
{"result":"value2\u4e2d\u6587"}
```

I want get like this:

```
{"result":"value2中文"}
```

**Comment by jonahfang** [comment]
In case you can not see chinese character:
![image](https://user-images.githubusercontent.com/16301509/28819100-ab38cb52-76df-11e7-8d3c-b064eff9da42.png)

**Comment by strahe** [comment]
Need to call the decode func:
```
result = await r.get('key')
r = result.decode()
```

r == 'value2中文'   # True

**Comment by jonahfang** [comment]
@strahe , it works , thank you very much!
