### ISSUE TITLE
Connection to two redis server

### ISSUE THREAD

**Issue by wasimbaig** [strahe/sanic-redis#5]
Firstly, thanks, this has been working really well, much appreciated.

Can you give an example on how to connect to two or more different redis servers? I can't seem to do it correctly, it always connects to only one. Thanks!

**Comment by strahe** [comment]
Hi, I just updated to 0.2.0, which supports configuring multiple instances.

See: https://github.com/strahe/sanic-redis#create-multiple-aioredis-instances
